services:
  events-platform-spring:
     build: .
     ports:
       - "8080:8080"
     environment:
       SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/events_platform?createDatabaseIfNotExist=true"
       SPRING_DATASOURCE_USER: root
       SPRING_DATASOURCE_PASSWORD: password

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: events_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: